# Generated by Django 4.1.7 on 2023-03-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.CharField(default=8.987552240147396e-05, max_length=255),
            preserve_default=False,
        ),
    ]
