# Generated by Django 4.1.7 on 2023-03-28 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 18, 12, 27, 521348, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
