# Generated by Django 4.1.7 on 2023-03-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
